### PR TITLE
Nomination pools API for Dart client

### PR DESCRIPTION
**Pull request by HolyGrease**
Because Dart client has issues with querying data directly from storage, we have to add RPC API for this.

- [x] Split RPC primitives so one file contains types for that RPC API
- [x] Add types for nomination pools (copy of types from pallet)
- [x] Add runtime API
- [x] Add RPC API

### CODE REVIEW

**Comment by avive** [comment]
It is wip right?

**Comment by HolyGrease** [comment]
> It is wip right?

Yes, you can see by todo list in the description section

**Comment by avive** [comment]
Just please add wip label and wip to to title...

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
