### PR TITLE
The way to add char trait and communities after genesis

### PR DESCRIPTION
**Pull request by HolyGrease**

### CODE REVIEW

**Review by avive — COMMENTED** [review]
Can you please document this in the readme regarding how this works with sudo?

**Comment by HolyGrease** [comment]
> Can you please document this in the readme regarding how this works with sudo?

It is easy enough. Sudo pallet have transaction called `call`. It can be called only by sudo account and except transaction to execute with sudo privilege as argument. So throw polkadot UI you need to go Developer > Extrinsics > Sudo > Call and in the arguments choose pallet appreciation and one of this transaction set arguments and sign

**Comment by avive** [comment]
Q: can Sudo remove a community admin from being an admin via call?

**Comment by HolyGrease** [comment]
> Q: can Sudo remove a community admin from being an admin via call?

Now not. Don't know that we need such functional. Should we added it in this PR?

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
