### PR TITLE
Add token symbol to display in polkadot ui

### PR DESCRIPTION
**Pull request by HolyGrease**

### CODE REVIEW

**Review by avive — COMMENTED** [review]
Q: does KC mean KCents or KCoins?
We want the base accounting unit to be KCents. I don't think there are decimals for it as there's no fractional KCents. 
So Kcnets is like Polkadot Plancks. See: 

"DOT is the native token of the Polkadot network. As the maximum number of DOT tokens is not predetermined, these tokens are inflationary in nature. However, the rate of inflation is variable. In the Polkadot ecosystem, the smallest divisible unit of a DOT token is called a “Planck.” One Planck is equivalent to 0.0000000001 DOT."

The requirements are:
- We need to design the coin so there's a high upper bounds on KCoins in circulation, say 5B.
- KCent is the basic accounting unit and there's no fractional KCents in the system. It is an int.
- One KCoin is 1M KCents.
- All internal coin operations should be done on KCents.

Refs
https://karmaco.in/docs/tokenomics#coin-units
https://www.bybit.com/en-US/coin-price/polkadot/

**Comment by HolyGrease** [comment]
> Q: does KC mean KCents or KCoins? We want the base accounting unit to be KCents. I don't think there are decimals for it as there's no fractional KCents. So Kcnets is like Polkadot Plancks. See:
> 
> "DOT is the native token of the Polkadot network. As the maximum number of DOT tokens is not predetermined, these tokens are inflationary in nature. However, the rate of inflation is variable. In the Polkadot ecosystem, the smallest divisible unit of a DOT token is called a “Planck.” One Planck is equivalent to 0.0000000001 DOT."
> 
> The requirements are:
> 
> * We need to design the coin so there's a high upper bounds on KCoins in circulation, say 5B.
> * KCent is the basic accounting unit and there's no fractional KCents in the system. It is an int.
> * One KCoin is 1M KCents.
> * All internal coin operations should be done on KCents.
> 
> Refs https://karmaco.in/docs/tokenomics#coin-units https://www.bybit.com/en-US/coin-price/polkadot/

By KC I mean KCoins because of that I set decimals equal to 6.
So because of requirements I think we should set `decimals = 0` and `symbol = KCents`

**Comment by avive** [comment]
> > Q: does KC mean KCents or KCoins? We want the base accounting unit to be KCents. I don't think there are decimals for it as there's no fractional KCents. So Kcnets is like Polkadot Plancks. See:
> > "DOT is the native token of the Polkadot network. As the maximum number of DOT tokens is not predetermined, these tokens are inflationary in nature. However, the rate of inflation is variable. In the Polkadot ecosystem, the smallest divisible unit of a DOT token is called a “Planck.” One Planck is equivalent to 0.0000000001 DOT."
> > The requirements are:
> > 
> > * We need to design the coin so there's a high upper bounds on KCoins in circulation, say 5B.
> > * KCent is the basic accounting unit and there's no fractional KCents in the system. It is an int.
> > * One KCoin is 1M KCents.
> > * All internal coin operations should be done on KCents.
> > 
> > Refs https://karmaco.in/docs/tokenomics#coin-units https://www.bybit.com/en-US/coin-price/polkadot/
> 
> By KC I mean KCoins because of that I set decimals equal to 6. So because of requirements I think we should set `decimals = 0` and `symbol = KCents`

I think that Karmachain should not know about KCs but only about KCents with 0 decimals.

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
