### PR TITLE
Importing users data from v1.0

### PR DESCRIPTION
**Pull request by HolyGrease**

### CODE REVIEW

**Comment by avive** [comment]
Can you please write a short bullet points on how the process works?

**Comment by avive** [comment]
Are there any tests for this? We should have basic ones.

**Comment by HolyGrease** [comment]
> Can you please write a short bullet points on how the process works?

When creating chain spec file we have option to specify backup file. If backup file specified genesis config will be extended with those backup data and all that data will be written into storage on genesis.

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
