### PR TITLE
Referral

### PR DESCRIPTION
**Pull request by HolyGrease**

### CODE REVIEW

**Comment by HolyGrease** [comment]
Current implementation works only for transaction happened in the same block. For further modification we need to add `timestamp` field to `CheckAccount` `SignedExtension`. Adding this field cause to error when interacting with a node from polkadot ui and polkadot api. So I create a support [issue](https://github.com/polkadot-js/api/issues/5662)

**Comment by avive** [comment]
Is this a complete solution that will work across blocks?
Do we have tests for it?

**Comment by HolyGrease** [comment]
> Is this a complete solution that will work across blocks?
> Do we have tests for it?

As I mentioned above we need support from polkadot api to test final solution

**Comment by avive** [comment]
So is this WIP or should be merged?

**Comment by HolyGrease** [comment]
I do not want to merge until we get response from polkadot devs how we can actually interact with our node after such changes

**Review by avive — APPROVED** [review]
LGTM

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
