### PR TITLE
Delete account feature

### PR DESCRIPTION
**Pull request by HolyGrease**

### CODE REVIEW

**Comment by avive** [comment]
checks fail...

**Comment by HolyGrease** [comment]
> checks fail...

Just need to rerun check...

**Comment by avive** [comment]
Please add test to no rewards for signup after deletion...

**Review by avive — CHANGES_REQUESTED** [review]
Can you please add tests?

**Review by avive — COMMENTED** [review]
Please clarify where funds go when account is deleted and that we have logic in place NOT to assign sign-up reward when an account with same phone number is created. We need to avoid this attack: 1. signup. 2. get signup reward. 3. move it to another wallet. 4. delete account. 5. go to step one with same phone number.

**Comment by HolyGrease** [comment]
> Please clarify where funds go when account is deleted and that we have logic in place NOT to assign sign-up reward when an account with same phone number is created. We need to avoid this attack: 1. signup. 2. get signup reward. 3. move it to another wallet. 4. delete account. 5. go to step one with same phone number.

When you delete your account all funds that remains on your account are burned (later we can change this to send them treasury for example).  Reward pallet keeps storing information per `AccountId` so signup with same keypair will not lead to abuse. But signup with new keypair will work, is it a problem?

**Comment by avive** [comment]
Signups with the same phone number should not reward the user with signup reward, even with a new keypair. I think we need to store an index of deleted accounts by phone number to support this feature.

**Comment by avive** [comment]
> Signups with the same phone number should not reward the user with signup reward, even with a new keypair. I think we need to store an index of deleted accounts by phone number to support this feature.

Is this implemented? Can we add integration tests in dart once this is merged?

**Pull request merged**
