### PR TITLE
Karma reward requires more appreciation

### PR DESCRIPTION
**Pull request by HolyGrease**

### CODE REVIEW

**Comment by avive** [comment]
Please confirm that they are rewarded according to the rules here https://karmaco.in/docs/tokenomics#karma-rewards

e.g. computed only once in a period and not every block.
Let's please have shorter period for devnet so we can add dart integration test for this as well.

**Review by avive — COMMENTED** [review]
above

**Comment by HolyGrease** [comment]
> Please confirm that they are rewarded according to the rules here https://karmaco.in/docs/tokenomics#karma-rewards
> 
> e.g. computed only once in a period and not every block. Let's please have shorter period for devnet so we can add dart integration test for this as well.

For dev environment we have period equal to 5 blocks

**Review by avive — APPROVED** [review]
LGTM

**Pull request merged**
